#!/bin/sh

begin_test() {
    printf "%s\n" "--------------------------------------------------------------------------------"
    printf "\033[1m% 80s\033[0m\n" "${@}"
}

end_test() {
    return
}

fail() {
    printf "\033[31;1m% 80s\033[0m\n" "${@}"
}

# splitting arguments desired
unset $(env | grep XDEB_ | sed 's/^\([^=]*\)=.*$/\1/g')

xdeb_dir="$(dirname -- "$(realpath -- "${0}")")"
test_dir="${xdeb_dir}/test"

xdeb_path="${xdeb_dir}/xdeb"

export XDEB_PKGROOT="${test_dir}/.pkgroot"
export XDEB_TEMPDIR="${test_dir}/.tmp"

# TODO allow subdirs
find "${test_dir}" -maxdepth 1 -mindepth 1 -type f -iname '*.test' -exec 'basename' '{}' ';' | while read -r d; do
    mkdir -p "${XDEB_TEMPDIR}/${d%.test}"
    cd "${XDEB_TEMPDIR}/${d%*.test}"

    xdeb -CcQ

    begin_test "${d}"
        . "${test_dir}/${d}"
        build
        run
    end_test
done
