#!/bin/sh

build() {
    mkdir -p path/to/empty/dir
    touch path/to/empty/file

    tee control >/dev/null <<EOF
Package: remove-empty-dirs
Version: 0
Architecture: all
Maintainer: none
Description:
 Test if removing empty directories works properly
EOF

    tar -cf control.tar control
    tar -cf data.tar */
    ar -rc package.deb control.tar data.tar
}

run() {
    "${xdeb_path}" -Se package.deb || fail "build failed"

    files="$(xbps-query --repository="${XDEB_PKGROOT}/binpkgs" -f remove-empty-dirs 2>&1)"

    echo "${files}" | grep "/path/to/empty/file" >/dev/null 2>&1 || fail "file also removed"
    echo "${files}" | grep "/path/to/empty/dir" >/dev/null 2>&1 && fail "dir not removed"
}
