#!/bin/sh

build() {
    mkdir -p usr/lib/dir
    mkdir -p lib/dir

    touch usr/lib/dir/usr_lib_dir
    touch lib/dir/lib_dir

    tee control >/dev/null <<EOF
Package: conflicting-with-existing-target
Version: 0
Architecture: all
Maintainer: none
Description:
 Test if merging conflicting directories with their destination works properly
EOF

    tar -cf control.tar control
    tar -cf data.tar */
    ar -rc package.deb control.tar data.tar
}

run() {
    "${xdeb_path}" -Sf package.deb || fail "build failed"

    files="$(xbps-query --repository="${XDEB_PKGROOT}/binpkgs" -f conflicting-with-existing-target 2>&1)"

    echo "${files}" | grep "/usr/lib/dir/usr_lib_dir" >/dev/null 2>&1 || fail "old /usr/lib/dir modified"
    echo "${files}" | grep "/usr/lib/dir/lib_dir" >/dev/null 2>&1 || fail "/lib/dir not merged with /usr/lib/dir"
}
